DSLNG.PEAR/DSLNG.PEAR.Web/Views/Menu/_SiteMap.cshtml

just fixed id, no other yet to define and still hardcoded

add id parameter on menu

---

DSLNG.PEAR/DSLNG.PEAR.Web/Web.Debug.config
DSLNG.PEAR/DSLNG.PEAR.Web/Web.config
DSLNG.PEAR/DSLNG.PEAR.sln

Revert "test transform"

---

DSLNG.PEAR/DSLNG.PEAR.Web/App_Start/BundleConfig.cs
DSLNG.PEAR/DSLNG.PEAR.Web/DSLNG.PEAR.Web.csproj
DSLNG.PEAR/DSLNG.PEAR.Web/Scripts/calculator.pricing.js
DSLNG.PEAR/DSLNG.PEAR.Web/Scripts/main.js
DSLNG.PEAR/DSLNG.PEAR.Web/ViewModels/Calculator/CalculatorIndexViewModel.cs
DSLNG.PEAR/DSLNG.PEAR.Web/ViewModels/Calculator/PricingViewModel.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Calculator/Index.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Calculator/_Pricing.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Web.config

calculator

---

DSLNG.PEAR/DSLNG.PEAR.Services/CalculatorConstantService.cs
DSLNG.PEAR/DSLNG.PEAR.Services/Requests/CalculatorConstant/SaveCalculatorConstantRequest.cs
DSLNG.PEAR/DSLNG.PEAR.Web/App_Start/BundleConfig.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/CalculatorConstantController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/DSLNG.PEAR.Web.csproj
DSLNG.PEAR/DSLNG.PEAR.Web/Scripts/calculator.constant.js
DSLNG.PEAR/DSLNG.PEAR.Web/Scripts/calculator.plant-availability.js
DSLNG.PEAR/DSLNG.PEAR.Web/Scripts/calculator.pricing.js
DSLNG.PEAR/DSLNG.PEAR.Web/Scripts/calculator.production-yield.js
DSLNG.PEAR/DSLNG.PEAR.Web/Scripts/main.js
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Calculator/Index.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Calculator/_PlantAvailability.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Calculator/_Pricing.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Calculator/_ProductionYield.cshtml

calculator can save constant now

---

DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/KpiAchievementController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/OperationDataController.cs

1st upload not null, 2nd upload null. It should be null.

bug fixing kpi achievement and operation data, case :

---

DSLNG.PEAR/DSLNG.PEAR.Web/ViewModels/PlanningBlueprint/PlanningBlueprintViewModel.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/PlanningBlueprint/Create.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/PlanningBlueprint/GetEconomicIndicators.cshtml

commit create dan modal

---

DSLNG.PEAR/DSLNG.PEAR.Web/Content/style.css
DSLNG.PEAR/DSLNG.PEAR.Web/Views/PlanningBlueprint/Approval.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/PlanningBlueprint/Index.cshtml

perubahan table untuk approval dan planning blueprint

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/PlanningBlueprint/MidtermPhaseFormulation.cshtml

ini tadi perubahan untuk header height pada mid term

ketinggalan bos

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/PopDashboard/Index.cshtml

saya telah menambahkan class untuk menambahkan border pada td dan juga memberi jarak spasi pada judul table.

penambahan border pada table pop dashboard

---

DSLNG.PEAR/DSLNG.PEAR.Services/Requests/Kpi/CreateKpiRequest.cs
DSLNG.PEAR/DSLNG.PEAR.Services/Requests/Kpi/UpdateKpiRequest.cs
DSLNG.PEAR/DSLNG.PEAR.Services/Responses/Kpi/GetKpiResponse.cs
DSLNG.PEAR/DSLNG.PEAR.Services/Responses/Kpi/KpiResponse/YtdFormula.cs
DSLNG.PEAR/DSLNG.PEAR.Web/ViewModels/Kpi/CreateKpiViewModel.cs
DSLNG.PEAR/DSLNG.PEAR.Web/ViewModels/Kpi/KpiViewModel.cs
DSLNG.PEAR/DSLNG.PEAR.Web/ViewModels/Kpi/UpdateKpiViewModel.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Kpi/Create.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Kpi/Update.cshtml

kpi configuration => aggregation formula, styling

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/MIR/Create.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/MIR/Edit.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/MIR/Index.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/MIR/_MirUpload.cshtml

Ø  Upload button di remove
Ø  kasih tanda remove upload file di MIR
Ø  Button X untuk menghapus file yang sudah terupload

Ø  saat create MIR, default isian MIR Month - 1 (previous month)

---

DSLNG.PEAR/DSLNG.PEAR.Web/Content/der-dikdik.css
DSLNG.PEAR/DSLNG.PEAR.Web/Content/style.css
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Artifact/Index.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/Input.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/EconomicSummary/Index.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Highlight/Display.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/PlanningBlueprint/VoyagePlan.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/PmsSummary/Index.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Scenario/Detail.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Shared/_Layout.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Template/Index.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Template/View.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/VesselSchedule/Manage.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Web.config

menambah css bootstrap dan melekengkapi option di form DerTransaction input

Merapihkan UI 

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/Shared/_Layout.cshtml

mas fajar cek ui pms, saya sudah benerin @fazar

reset layout

---

DSLNG.PEAR/DSLNG.PEAR.Web/Content/der-dikdik.css

saya udah balikin file der-dikdik.css ke semuala, tolong di merge mas @fazar

balikin file der-dikdik.css

---

DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/KpiController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/ViewModels/Kpi/KpiViewModel.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Kpi/Create.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Kpi/Update.cshtml

Add NaN Value for YtdFormula in ViewModel

Add on Change KPI Configuration Create/Edit

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Display/_LngAndCds.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Kpi/Create.cshtml

form input bagian LNG cargo, JER belum kepointing ke kpi id 240, trus yg firld target belum ngeload kpi2 terkait.

form input bagian LNG cargo, JER belum kepointing ke kpi id 240, trus yg firld target belum ngeload kpi2 terkait.

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Display/_LngAndCds.cshtml

DER Preview	bagian remarknya di merge klo format agustus

DER Preview	bagian remarknya di merge klo format agustus

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Display/_LngAndCds.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/OperationSection.cshtml

LNG Loaded Remak
Der Transaction
Der Preview

LNG Loaded Remak Der Transaction Der Preview

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Display/_CriticalPm.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/MaintenanceSection.cshtml

Remark Critical PM's

---

DSLNG.PEAR/DSLNG.PEAR.Model/Entities/User.cs
DSLNG.PEAR/DSLNG.PEAR.Services/Requests/User/CreateUserRequest.cs
DSLNG.PEAR/DSLNG.PEAR.Services/Requests/User/UpdateUserRequest.cs
DSLNG.PEAR/DSLNG.PEAR.Services/Responses/User/GetUserResponse.cs
DSLNG.PEAR/DSLNG.PEAR.Services/Responses/User/GetUsersResponse.cs
DSLNG.PEAR/DSLNG.PEAR.Services/UserService.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/UserController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/ViewModels/User/CreateUserViewModel.cs
DSLNG.PEAR/DSLNG.PEAR.Web/ViewModels/User/UpdateUserViewModel.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Display/_LngAndCds.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/User/Create.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/User/Update.cshtml

Add Upload Signature upon User Creation
Fix Signature handling while User Update
Fix Mapping for LNG Loaded Remark in DER Preview

Add Position in User Properties

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/Input.cshtml

Change Default Date Value on Custom Form Input to Current Date - 1

Change Default Date Value on Custom Form Input to Current Date - 1

---

DSLNG.PEAR/DSLNG.PEAR.Services/DerTransactionService.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/DerTransactionController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Helpers/HtmlHelpers.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/EconomicIndicator.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/InputData/FormInputData.cshtml

prev-data-form-input

---

DSLNG.PEAR/DSLNG.PEAR.Services/DerTransactionService.cs

add periode type to where clause - Cerrypick from fazar Merge

add periode type to where clause - Cerrypick from fazar Merge

---

DSLNG.PEAR/DSLNG.PEAR.Services/CustomFormulaService.cs
DSLNG.PEAR/DSLNG.PEAR.Services/Interfaces/IKpiAchievementService.cs
DSLNG.PEAR/DSLNG.PEAR.Services/KpiAchievementService.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/DerTransactionController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/DependencyResolution/DefaultRegistry.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Helpers/HtmlHelpers.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Preview3.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/EconomicIndicator.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/EnablerSection.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/Input.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/OperationSection.cshtml

DER Transaction Custom Transaction Handler, process Feed Gas (GSA) : JOB & MGDP, LNG Price (SPA): FOB Value on Custom Input transaction process when Applied JCC Inserted
LNG Price (SPA) : DES will be processed upon Monthly Bunker Price transaction

CR Sept DSLNG Indicative Commercial Item #6

---

DSLNG.PEAR/DSLNG.PEAR.Web/Helpers/HtmlHelpers.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Display/_PlantAvalability.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/Input.cshtml

2. Terkait dengan format september untuk Area Total Fuel Gas (GTG-GTC-LP Fuel), 3 value itu harusnya Daily As Of sekarang kayaknya YTD dan gak ada konfigurasinya utk milih period as of. Aku dah konfigurasi pointing KPInya yg benar di Staging.	
Form Input Der:
1.Semua default value hari sebelumnya jika depannya contoh 0.1 cuma tertampil .1, kalo dienter baru muncul semua. 
2.Semua defult value hari sebelumnya jika 0 tidak tampil. 
3.Semua field Date belum terisi defult value hari sebelumnya yaitu:
A. CDS Loaded-Note ->> field kekunci number harusnya text, default value hari sebelumnya belum muncul
B. CDS Loaded-Remark ->> field kekunci number harusnya text, default value hari sebelumnya belum muncul
C. Marine, Shipping, Cargo Delivery Highlight

Bug Fix 10-17-2016

---

DSLNG.PEAR/DSLNG.PEAR.Services/Interfaces/IKpiTransformationScheduleService.cs
DSLNG.PEAR/DSLNG.PEAR.Services/KpiTransformationScheduleService.cs
DSLNG.PEAR/DSLNG.PEAR.Services/Responses/KpiTransformationSchedule/GetKpiTransformationSchedulesResponse.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/KpiTransformationController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/KpiTransformation/Log.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/KpiTransformation/LogDetails.cshtml

Log ->Back To List KPI Transformation
Log Detail -> Back To List of Log

Log ->Back To List KPI Transformation

---

DSLNG.PEAR/DSLNG.PEAR.Web/Helpers/HtmlHelpers.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/EconomicIndicator.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/EnablerSection.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/Input.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/OperationSection.cshtml

20, Economic Indicator dan Forecasted indicator lebar field max 10 digit.
21. Min HHV jaraknya kejauhan dengan mche.

10. Sea condition option. Semua pake &, check option text.

---

DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/DerLoadingScheduleController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Helpers/HtmlHelpers.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerLoadingSchedule/AddBuyer.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerLoadingSchedule/AddVessel.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerLoadingSchedule/Create.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerLoadingSchedule/Edit.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/EconomicIndicator.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/EnablerSection.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/Input.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/MaintenanceSection.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/MarineShipping.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/OperationSection.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/QhsseSection.cshtml

…t DES/FOB -> done
2.Add new NLS. Field DES/FOB di option list Default label ganti Select Cargo Type -> done
3.Link Add New vessel dan add New buyer belum muncul di form add New NLS  -> on-progress
3.Warna tombol save nls di kontrasin(kuning) -> done
4.Semua remark yg no text area kita lebarin fieldnya. -> perlu bantuan list field yang akan dilebarkan
5.Font header > subtitle ini sepertinya belum, krn fontnya masih sama sizenya. ->h5->subtitle->normal : 14px;13px;12px;
6.Area Enabler check lagi Check lagi Warna sub group, tanda : -> done
7.Procurement section semua field kecuali remark dibuat lebar 3 digit. -> drop down tidak memungkinkan untuk 3 digit, akan jomplang
8.LNG Loaded Remark kurang : -> done
9.Actual Daily Shipped   CDS turun satu row jaraknya -> masih belum jelas
10. Label …

Bug Report 31 Oktober 2016

---

DSLNG.PEAR/DSLNG.PEAR.Services/VesselScheduleService.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerLoadingSchedule/Edit.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/Input.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/MarineShipping.cshtml

Save Default Value from placeholder (value not edited but saved as current value)
Typo on DerLoadingSchedule/Edit : data.VesseMeasuremant -> data.VesselMeasuremant
change tabindex after save schedule from 176 -> 171 (change element index cause this behaviour)

Save Default Value from placeholder (value not edited but saved as current value)

---

DSLNG.PEAR/DSLNG.PEAR.Services/InputDataService.cs
DSLNG.PEAR/DSLNG.PEAR.Services/Interfaces/IInputDataService.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Content/style.css
DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/DerController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/DerLayoutController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/InputDataController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/KpiTransformationController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Display/_PersonOnBoard.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Index.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerLayout/EditLayoutItem.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/EnablerSection.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/DerTransaction/Input.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/InputData/Index.cshtml
DSLNG.PEAR/DSLNG.PEAR.Web/Views/KpiTransformation/Index.cshtml

add outline for textarea
add delete function on input data grid
add delete function on kpi transformation grid

fix decimal value for person on Board

---

DSLNG.PEAR/DSLNG.PEAR.Services/KpiTransformationService.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Helpers/HtmlHelpers.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Scripts/der-scripts.js

a. Series Label & Fraction
b. change decimal places

finding 2016-11-30

---

DSLNG.PEAR/DSLNG.PEAR.Web/Helpers/HtmlHelpers.cs

cherypick to 177293b1733b2ee6e07a1cb075bce746b47f9ba2 commit
on Nov 19th 2016

Restore PlantAvailability

---

DSLNG.PEAR/DSLNG.PEAR.Services/ArtifactService.cs
DSLNG.PEAR/DSLNG.PEAR.Services/DerService.cs

will be affect to artifact too

Barmeter & Speedometer set data not to latest value

---

DSLNG.PEAR/DSLNG.PEAR.Services/ArtifactService.cs

affected to artifact preview 12 and DER Preview

Add Filter Query for Speedo Meter and barmeter

---

DSLNG.PEAR/DSLNG.PEAR.Web/Controllers/KpiController.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Scheduler/KpiTransformationJob.cs
DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Preview3.cshtml

re-apply manual input filter on KPI Config
patch for bug reported on tgl 26 Jan 17

remove filter for KPI 37&8 data transformation job

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Preview3.cshtml

Perbaikan laporan anomaly DER preview 7 Mar

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/InputData/FormInputData.cshtml

PEAR BUG 13 Mar

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Display/_CriticalPm.cshtml

Judul Tabulasi DER - Maintenance

---

DSLNG.PEAR/DSLNG.PEAR.Services/Responses/User/GetUserResponse.cs
DSLNG.PEAR/DSLNG.PEAR.Services/UserService.cs

http://trac.regawa.com/issues/2076

http://trac.regawa.com/issues/2076

---

DSLNG.PEAR/DSLNG.PEAR.Web/Views/Der/Display/_IndicativeCommercialPrice.cshtml

http://trac.regawa.com/issues/2187

Perubahan Label di Indicative Commercial Price #issues#2187

---

DSLNG.PEAR/DSLNG.PEAR.Services/UserService.cs

https://github.com/DSLNG/Pear/commit/6e3176ffd5b3038518cb1cca24ed3c396b8e6a69

Login with username or email
